### ISSUE TITLE
unable to integrate Sitecore rocks 4.0.291 with VS 2019

### ISSUE THREAD

**Issue by abhinavssingh** [Sitecore/Sitecore.Rocks#143]
Hi, 

Trying to integrate Sitecore rocks 4.0.291 with VS 2019 but getting below error while i have applied web.config changes as per [here](https://sitecorecompetencies.com/2018/07/31/sitecore-rocks-unable-to-connect-with-sitecore-9/)

Visual studio version is 
Microsoft Visual Studio Professional 2019
Version 16.5.5
.NET framework version is 4.8

![rocks](https://user-images.githubusercontent.com/36994657/82109157-818f0380-9751-11ea-8c53-80dd5be620c0.jpg)

**Comment by nickwesselman** [comment]
This was addressed via Twitter.

https://twitter.com/AbhinavKSingh06/status/1261690997379080194
