### ISSUE TITLE
Icons missing from Set Icon dialog

### ISSUE THREAD

**Issue by mjftechnology** [Sitecore/Sitecore.Rocks#92]
The Icon dialog currently fails to show any icons. Rocks is getting a bunch of 404 errors when attempting to retrieve the icons. This appears to be down to the repo moving from https://github.com/JakobChristensen/Sitecore.Rocks to https://github.com/Sitecore/Sitecore.Rocks

Raised PR here:
[https://github.com/Sitecore/Sitecore.Rocks/pull/91](https://github.com/Sitecore/Sitecore.Rocks/pull/91)

Screenshot of problem:

![image](https://user-images.githubusercontent.com/16286329/54919127-e78a4d00-4ef7-11e9-9cdd-3f8c13d1f9f7.png)

**Comment by nickwesselman** [comment]
Resolved, thank you!
