### ISSUE TITLE
Can't drag & drop items in VS Community 2017 on Rocks 3.0

### ISSUE THREAD

**Issue by andrewvieau** [Sitecore/Sitecore.Rocks#96]
I can use the clipboard > cut / paste functionality, but drag & drop does not have any effect on items.

This affects moving items to a new location, as well as re-ordering items in the content tree.

**Comment by nickwesselman** [comment]
Nice catch. Reproduced in VS19 as well. At least in part related to an error some code changes required to support `AsyncPackage`, but even with that fix, things don't seem to be refreshing properly after a move.

**Comment by nickwesselman** [comment]
This should be resolved in latest build, with the caveat of existing issue #97. Have a minute to confirm @andrewvieau?

https://ci.appveyor.com/api/buildjobs/bv84wdonp8sgy641/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix

**Comment by andrewvieau** [comment]
@nickwesselman Confirmed, drag & drop does appear to be working now.

**Comment by nickwesselman** [comment]
Awesome thank you!
