### ISSUE TITLE
Suggestion: Default to ALL rather than RECENT when adding renderings or new items

### ISSUE THREAD

**Issue by andrewvieau** [Sitecore/Sitecore.Rocks#99]
This is a small issue that only affects people the first time they add new items or components after installing Sitecore Rocks.

When you use the Add New Item or Add Rendering dialogue for the first time, Sitecore Rocks will default to Recent - resulting in zero selections being available.

It would be preferable to default to All.

![image](https://user-images.githubusercontent.com/2454839/57802653-12389b00-771c-11e9-94c0-6c92b84d6ac1.png)

![image](https://user-images.githubusercontent.com/2454839/57802719-37c5a480-771c-11e9-9ce9-c91b1733de92.png)

**Comment by nickwesselman** [comment]
Thanks @andrewvieau, this is good feedback. Perhaps dynamically default to All only if Recent is empty?

**Comment by andrewvieau** [comment]
That would be nice too.

Though to be honest, I never use Recent. Can't speak for anyone else for sure, but I just switch it to All and never look back.

**Comment by nickwesselman** [comment]
Following up on this... since the dialogs remember the last selected filter, if you want to use Recent after having selected something, it will remain on Recent after you use it, if so desired. Since first use won't have any recent items, totally makes sense for All to be the default.

**Comment by nickwesselman** [comment]
Updated in `develop`, will be in next Rocks release
